P3
elagarrigue/AyDS21-AK-Apolo1 pull request #2
Opened 2021-05-15 00:08 UTC by Brunoo886

2021-05-17 00:51 UTC, RomanVila commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private val lastFMAPI = createEndPoint()
createEndPoint no es un buen nombre

2021-05-17 01:13 UTC, RomanVila commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        }
Eliminar líneas vacías.
El valor de width debería definirse en una constante.

2021-05-17 01:14 UTC, RomanVila commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        "[*] ${getInfo(dataBase, artistName)}"
El prefijo [*] debería definirse en una constante.

2021-05-17 01:16 UTC, RomanVila commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/DataBase.kt
> +        fun getInfo(dbHelper: DataBase, artist: String): String? {
A qué info hace referencia el nombre del método? Renombrar.

2021-05-17 01:23 UTC, RomanVila commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/DataBase.kt
> +        }
Este método inicializa una serie de arreglos y strings y retorna el resultado de una consulta a la base de datos: queryCreation no es un buen nombre.
Además, hay que definir constantes para los strings que están hardcodeados.

2021-05-17 01:26 UTC, RomanVila commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/DataBase.kt
> +        private fun getResults(cursor: Cursor): String? {
Renombrar para que quede clara la intención de este método, que recibe un Cursor y retorna un String.
La MutableList es completamente necesaria?

2021-05-17 01:27 UTC, RomanVila commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/DataBase.kt
> +            values.put("source", 1)
Definir constantes para estos Strings.

2021-05-17 01:27 UTC, RomanVila commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/DataBase.kt
> +            dbHelper.writableDatabase.insert("artists", null, values)
Definir constante para "artists"

2021-05-17 01:34 UTC, RomanVila commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun getArtistInfo(artistName: String) {
Mañana conversemos sobre cómo mejorar getArtistInfo y getBioContentFromService.

2021-05-18 04:15 UTC, Brunoo886 commented
El equipo de Apolo 1 pide disculpas por el tiempo demorado en ultimar correcciones.

Buenas noches!

2021-05-19 00:05 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun getArtistInfo(artistName: String) {
Este sería el algoritmo del repositorio. Deberia retornar un resultado String y no utilizar la variable artistInfoContent para guardar los resultados. Luego una vez obtenido ese resultado se utiliza para actualizar la vista

2021-05-19 00:06 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun getArtistData() {
getArtistData es un nombre que se confunde con getArtistInfo, usar otro nombre

2021-05-19 00:07 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            intent.getStringExtra(ARTIST_NAME_EXTRA)?.let {
Usar un método aparte para obtener el nombre del artista.

```suggestion
        val artistName = getArtistName()
        Thread {
            val artistInfo = getArtistInfo(name)
             showMoreDetails(artistInfo)    
        }
```

2021-05-19 00:30 UTC, RomanVila requested changes

2021-05-19 00:30 UTC, RomanVila commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    }
Al haber agregado la URL en la base de datos, lo ideal sería hacer una única query que dado un artist retorne todo. 
De esa manera, evitamos esta situación de invocar primero a `getInfoArtist` y luego a `getUrl`, con el costo que implica hacer las dos consultas a la base de datos (les dejo un comentario en Database.kt relacionado a esto).

2021-05-19 00:30 UTC, RomanVila commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/DataBase.kt
> +        fun getInfoArtist(dbHelper: DataBase, artist: String): String? {
Al haber agregado la URL en la base, ahora deberían unificar `getInfoArtist` y `getUrl`, de modo que retorne los dos datos a partir de un artist. De esa manera, evitamos la doble consulta a la base de datos.

2021-05-21 12:30 UTC, RomanVila commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
>      }
Vamos a mejorar el método del repositorio.
Los métodos **existsInLocalDB** y **getArtistInfoFromLocalDB** ejecutan cada uno una consulta a la base de datos. Esto debería evitarse para no degradar la performance. Entonces (va pseudocodigo):

```
getArtistInfo(artistName)
	artistInfo <-- DB.getArtistInfo(artistName)
        if existsInDB(artistInfo) // existsInDB es simplemente un método que retorna el valor de artistInfo != null
            artistInfo <-- getArtistInfoBioContentFromLocalDB (renombrar a handleLocalArtistInfo o processLocalArtistInfo)
        else
            artistInfo <-- getArtistInfoFromService(artistName)
            saveArtistInDataBase(artistName, artistInfo)
```

getArtistInfoFromService(artistName)
Este método obtiene el json del servicio e invoca a otro método (tambien handleArtistInfoFromService o processArtistInfoFromService) que se encarga de procesar la info y la URL, y retorna la ArtistInfo.

2021-05-21 12:30 UTC, RomanVila commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/DataBase.kt
>              "create table artists (" +
Usar constante para "artists"

2021-05-21 12:30 UTC, RomanVila commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/DataBase.kt
Eliminar línea vacía de más.

2021-05-22 23:43 UTC, RomanVila approved these changes

2021-05-22 23:43 UTC, merged