P4
elagarrigue/AyDS21-AK-Apolo1 pull request #3
Opened 2021-06-04 20:18 UTC by NachoOlivero

2021-06-06 00:34 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/ArtistInfoRepository.kt
> +                    Log.e("LastFM Info", "ERROR: $e")
e.printStackTrace()

2021-06-06 00:34 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/ArtistInfoRepository.kt
> +        Log.e("LastFM Info", "song $artistInfo")
Borrar Log

2021-06-06 00:34 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/ArtistInfoRepository.kt
> +        artistInfo.info =
Fijense que en home no está esto. Poner el asterisco es algo visual, ergo, no correponde al repositorio

2021-06-06 00:34 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/external/lastFM/LastFmModule.kt
> +    private val textFormatter: TextFormatter = TextFormatterImpl()
Cuidado, todo lo que tiene que ver con formato de texto es algo visual. No es responsabilidad del repositorio

2021-06-06 00:34 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/external/lastFM/artistInfo/LastFMArtistInfoServiceImpl.kt
> +        Log.e("LastFM call response", " $callResponse")
Borrar logs

2021-06-06 00:34 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/external/lastFM/artistInfo/TextFormatter.kt
> +        builder.append("<html><div width=$HTML_DOC_WIDTH>")
Con Kotlin:

```suggestion
       builder.apply {
         append(...)
         append(...)
      }
```

2021-06-06 00:34 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
> +private const val LASTFM_LOGO_IMAGE_URL =
La default image al State

2021-06-07 22:41 UTC, RomanVila requested changes
Hay que hacer unos ajustes al diagrama:
* LastFMLocalStorage conoce a CursorToInfoMaper (falta flecha en esa dirección)
* LastFMArtistInfoService conoce a LastFMAPI y a LastFMToArtistInfoResolver (faltan flechas en esas direcciones)
* Deberían agregarse flechas desde ArtistInfoRepository a los paquetes local.lastfm y external.lastfm
* Eliminar la flecha de LastFMArtistInfoService a InfoArtist
* Agregar flecha desde View a Model

2021-06-08 22:56 UTC, kevschweitzer requested changes
Sobre el diagrama:

- Agregar la flecha de MoreDetailsModel a Repository

2021-06-08 22:56 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/ArtistInfoRepository.kt
> +                        artistInfoLocalStorage.saveArtist(artistName, it)
Chequeen que en el paquete Home en esta instancia se chequea si el dato ya esta guardado en la BD y en ese caso solo se hace un update.

2021-06-08 22:56 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/local/lastFM/LastFmLocalStorage.kt
> +    fun saveArtist(query: String, artistInfo: InfoArtist)
Fijense que query, ademas de mal nombre,  es el nombre del artista, que ya está en artistInfo, por lo tanto no es necesario

2021-06-08 22:56 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/local/lastFM/sqldb/LastFMLocalStorageImpl.kt
> +private const val DATABASE_NAME = "dictionary.db"
Cambiar el nombre de la Base de datos a algo que represente artists

2021-06-08 22:56 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/local/lastFM/sqldb/LastFMLocalStorageImpl.kt
> +
Linea de más

2021-06-12 04:14 UTC, kevschweitzer approved these changes

2021-06-12 04:15 UTC, merged