P5
elagarrigue/AyDS21-AK-Apolo1 pull request #4
Opened 2021-06-18 19:58 UTC by NachoOlivero

2021-06-20 01:54 UTC, kevschweitzer requested changes
Buenas chicos!

Algunas correcciones generales:

- La clase Card debe ser interna al proyecto, no debe estar en el submodulo, y debe ser un mapeo de la informacion del artista. (no debe haber referencia al nombre Card en el submodulo). Ustedes deben recibir la informacion del artista y ver en ese momento que datos les dió. En el caso de ser validos el repository devolverá una Card correcta (previo guardado en DB) y en caso de ser incorrecto (por ejemplo porque devolvio null) deben devolver una EmptyCard.

- El sufjo `impl` no se usa con clases que representan modelos. Pueden hacer que Card sea una open class y que EmptyCard herede de ella.

- Ahora van a cambiar el nombre Card pero fijense que el servicio del submodulo devuelve `CardImpl`. Deberian devolver la clase mas general en ese caso

- isLocallyStored tambien es algo interno, no debe estar en al respuesta del servicio. El servicio es independiente de si ustedes guardan o no el dato en la base de datos.

- Actualicen el UML con el nuevo cambio del submodulo

Puede ser que tenga ssh el nuevo submodulo? No lo pude clonar. Ustedes tuvieron que poner alguna contraseña o agregar su ssh al repositorio de Bruno para clonarlo?

2021-06-20 05:39 UTC, Brunoo886 commented
La clase Card debe ser interna al proyecto, no debe estar en el submodulo, y debe ser un mapeo de la informacion del artista. (no debe haber referencia al nombre Card en el submodulo). Ustedes deben recibir la informacion del artista y ver en ese momento que datos les dió. En el caso de ser validos el repository devolverá una Card correcta (previo guardado en DB) y en caso de ser incorrecto (por ejemplo porque devolvio null) deben devolver una EmptyCard. //FIXED

Ahora van a cambiar el nombre Card pero fijense que el servicio del submodulo devuelve CardImpl. Deberian devolver la clase mas general en ese caso //FIXED

isLocallyStored tambien es algo interno, no debe estar en al respuesta del servicio. El servicio es independiente de si ustedes guardan o no el dato en la base de datos. //FIXED

2021-06-20 06:23 UTC, Brunoo886 commented
El sufjo impl no se usa con clases que representan modelos. Pueden hacer que Card sea una open class y que EmptyCard herede de ella. //FIXED

2021-06-21 01:24 UTC, Brunoo886 commented
Puede ser que tenga ssh el nuevo submodulo? No lo pude clonar. Ustedes tuvieron que poner alguna contraseña o agregar su ssh al repositorio de Bruno para clonarlo?

-RE: Nosotros utilizamos el GitHub Desktop, que no necesitamos acceder al git Bash para clonar etc. Estamos averiguando cómo hacer que se pueda clonar.

2021-06-22 22:34 UTC, kevschweitzer requested changes

2021-06-22 22:34 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/ArtistCardRepository.kt
> +                    val artistInfo = artistInfoTrackService.getArtistInfo(artistName)
Esto seria lo mismo no?

```suggestion
artistInfoTrackService.getArtistInfo(artistName).let {
    artistCard = artistInfoToCardMapper.map(it)
    when {
        isSavedSong(artistName) -> artistCardLocalStorage.updateArtistCard(it, artistName)
        else -> artistCardLocalStorage.saveArtistCard(it, artistName)
    }
}
```

2021-06-22 22:34 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/ArtistCardRepository.kt
> +                            isSavedSong(artistName) -> artistCardLocalStorage.updateArtistCard(it,artistName)
isSavedSong esta chequeando lo mismo que chequean arriba, osea que el getArtistCardByName sea distinto de nulo. El update no es necesario en este caso.

(Creo que era una corrección que habia hecho antes comparando con Home pero no aplica a este caso)

2021-06-22 22:34 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/local/lastFM/ArtistInfoToCardMapper.kt
> +    override fun map(artistInfo: ArtistInfo): Card {
Mejora de código

```suggestion
    override fun map(artistInfo: ArtistInfo) = Card(
        description = artistInfo.description,
            infoUrl = artistInfo.infoUrl,
            sourceLogoUrl = artistInfo.sourceLogoUrl,
            source = Source.LAST_FM
    )
```

2021-06-22 22:34 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsUiState.kt
> +    val artistCardSource: Source = Source.EMPTY_SOURCE,
La vista solo se interesa por el texto del source, no el enumerado. Seria mejor que artistCardSource sea un String y hacer el getSource() cuando hacen el update del state

2021-06-22 22:34 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
> +
Linea de más

2021-06-22 22:34 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
> +            artistCardSource = artistCard.source,
Aca seria el getSource()

2021-06-22 22:34 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
> +            actionsEnabled = false,
esta coma no hace falta

2021-06-24 00:21 UTC, kevschweitzer requested changes

2021-06-24 00:21 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/ArtistCardRepository.kt
> +                        artistCardLocalStorage.saveArtistCard(it, artistName)
Esta linea mejor dentro del let anterior o no? Es el mismo chequeo ya que el resultado se asigna a artistCard

2021-06-24 00:30 UTC, kevschweitzer approved these changes

2021-06-24 00:31 UTC, merged