P6
elagarrigue/AyDS21-AK-Apolo1 pull request #5
Opened 2021-07-05 22:19 UTC by Brunoo886

2021-07-06 23:10 UTC, kevschweitzer submitted a review, later dismissed
- Cuando no hay resultados aparece el botón de View Full Article y crashea al apretarlo

Comentarios sobre el UML
- La herencia de los proxies deberia ser una linea concreta
- Las librerias externas no están dentro de la carpeta Model
- Lo correspondiente a broker y proxies deberian estar una carpeta `broker`

2021-07-06 23:10 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
> +        if (spinnerList.isEmpty())
Si está vacio directamente escondan el Spinner y dejen en la pantalla el estado de "no results"

2021-07-06 23:10 UTC, kevschweitzer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
> +                    artistCards = listOf(EmptyCard),
Mejor usen lista vacia como estado Empty

2021-07-09 21:43 UTC, RomanVila commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/ArtistCardRepository.kt
>              }
Mover todo un tab a la izquierda para alinear bien el if - else

2021-07-09 21:44 UTC, RomanVila commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/external/ExternalModule.kt
> +
Línea de más

2021-07-09 21:44 UTC, RomanVila commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/external/LastFMProxy.kt
> +                source = Source.LAST_FM
Mover todo un tab a la izquierda

2021-07-09 21:45 UTC, RomanVila commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/external/NYTimesProxy.kt
> +                source = Source.NYTIMES
Mover todo un tab a la izquierda

2021-07-09 21:45 UTC, RomanVila commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/external/WikipediaProxy.kt
> +                source = Source.WIKIPEDIA
Mover todo un tab a la izquierda

2021-07-09 21:58 UTC, RomanVila commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
>          }
```
if (artistCards.isNotEmpty()) {
    uiState = uiState.copy(
        artistCards = artistCards,
        actionsEnabled = true
    )
}
```

2021-07-09 22:18 UTC, RomanVila requested changes
Sobre el diagrama:
* Es incorrecto poner al Model en parte adentro y en parte afuera de moredetails. Es decir, LastFMData es ahora un servicio externo, como NewYorkTimes y Wikipedia. Por eso, no debería estar adentro del Model.

* CardLocalStorage está repetido.

* ArtistCardRepository no debería estar dentro del broker, sino afuera (al nivel de repository). A su vez, ArtistCardRepository conoce tanto a CardLocalStorage como a ArtistCardBroker. Entonces, las flechas que salen de él deben llegar a local.lastfm y broker.

* La flecha que sale de MoreDetailsModel debe llegar a repository, no a ArtistCardRepository,

2021-07-09 22:56 UTC, RomanVila approved these changes

2021-07-09 22:57 UTC, merged